### ISSUE TITLE
Config option to enable/disable Gatekeeper

### ISSUE THREAD

**Issue by dennisfrank** [tomdiggle/craft-gatekeeper#7]
It would be super awesome if one could enable/disable Gatekeeper via a config option. In a staging environment I would like to have Gatekeeper enabled but locally I don’t need it. 

Therefore I would use environment variables from the `.env` file.

```php
return [

    "enabled" => getenv('GATEKEEPER_ENABLED'),
    "password" => getenv('GATEKEEPER_PASSWORD'),
    "notice" => '',

];
```

**Comment by dennisfrank** [comment]
I forgot. For a Live environment it would also be important to disable Gatekeeper programmatically.

**Comment by tomdiggle** [comment]
Thanks, I'll try add this feature asap 👍

**Comment by dennisfrank** [comment]
Thanks @tomdiggle! Works great.
